### ISSUE TITLE
Error when opening a new split window in tmux

### ISSUE THREAD

**Issue by AreUGroot** [luk400/vim-jukit#14] opened 2022-07-10 02:28 UTC
Laptop information:

* OS: macOS 12.3
* iTerm version: 13.4.5
* tmux version: 3.2a

The following error message appeared when I typed <leader>os or `call jukit#splits#output()`
```vim
Error detected while processing function jukit#splits#output[8]..jukit#tmux#splits#│ output[2]..jukit#tmux#cmd#launch[2]..<SNR>149_system:
line 5:
E714: List required
```

Is there anything wrong with my settings? Thank you!

**Comment by luk400** [comment] 2022-07-10 08:22
Hi, thanks for making me aware of this. It should be fixed now, please reinstall the plugin and try again.

**Comment by AreUGroot** [comment] 2022-07-11 01:23
Thanks! It works and I am able to open the ipython panel in tmux, though there are some other issues. The split layout is different from the expected layout, the even vertical layout. The ipython pane zooms in more than half of the space.

By the way, there are two more issues. The cursor goes to the ipython pane, not the vim pane at the beginning. After moving the cursor to the vim pane, I have to press `q` to reveal the file in vim.  The screenshot is posted below.

<img width="1855" alt="Figure1" src="https://user-images.githubusercontent.com/109008709/178171686-510aed97-14c8-4ae4-94a8-759f327271bd.png">

**Comment by luk400** [comment] 2022-07-11 05:47
Interesting, I will try to reproduce your issue today in the evening, meanwhile could you make sure you have the right iterm2 build? I'm not sure what version 13.4.5 is or if that's just a typo, but I only tested it on build 3.4.15.

**Comment by AreUGroot** [comment] 2022-07-11 16:21
> Interesting, I will try to reproduce your issue today in the evening, meanwhile could you make sure you have the right iterm2 build? I'm not sure what version 13.4.5 is or if that's just a typo, but I only tested it on build 3.4.15.

Sorry for the typo. My iterm2 was downloaded from the official website and it has been working well. Btw I'm using zsh as default shell.

**Comment by luk400** [comment] 2022-07-12 17:46
Everything works as expected for me with iterm2 build 3.4.15 and tmux 3.2a, but that's on a fresh install of Big Sur. I'll have to see if I can get a MacOS Monterey VM running to further debug this

**Comment by luk400** [comment] 2022-07-12 18:04
Also, are you using a custom config file for tmux?

**Comment by luk400** [comment] 2022-07-12 21:16
alright so I was able to reproduce the issue with a fresh install of macOS Monterey. It occurs using both Vim 8.2 and Vim 9. I'll have time to look into it further by the end of the week.

**Comment by luk400** [comment] 2022-07-13 16:22
Update: Your described problem actually only occured for me when using the wrong tmux version. Please uninstall tmux using `brew uninstall tmux` and install the exact version I just tested on using the following commands:
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/e44425df5a8b3c8c24073486fa7e355f3ac19657/Formula/tmux.rb
brew install ./tmux.rb
tmux -V # make sure it says tmux 3.2a
brew pin tmux # prevent unintentional upgrade in the future
```

Exit and restart your tmux session in case you executed the above commands from within tmux and afterwards everything (including the plots) should work as expected.

**Comment by AreUGroot** [comment] 2022-07-13 18:26
Thank you! The split layout works as expected now, while the inline figure shows in a wrong place. It appears on the left pane covering the codes. Could you please have a look on this issue?

<img width="1805" alt="Figure1" src="https://user-images.githubusercontent.com/109008709/178804443-28357093-d302-4f94-932b-190e324f82ff.png">
.

**Comment by luk400** [comment] 2022-08-26 07:32
closing due to inactivity

**Closed by luk400** 2022-08-26 07:32 UTC
Labels: bug

**Comment by nikisix** [comment] 2023-10-26 17:09
I'm having the same issue as @AreUGroot. I checked the panes, and the output pane is correct (even though current_pane is blank) (more info here: #101).

That's good to know about how imgcat.py is working. I'll have to check that next.
